name: GitHub Crawler Assignment


on:
  push:
    branches: [ "main" ]  
  workflow_dispatch:      



jobs:
  crawl-and-dump:
    runs-on: ubuntu-latest

    # Service Container: Postgres
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: github_data
        ports:
          - 5432:5432
        
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup Database Schema
        run: python main.py --mode=setup
        env:
         
          DB_URL: postgresql://user:password@localhost:5432/github_data

      - name: Crawl Stars
        run: python main.py --mode=crawl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DB_URL: postgresql://user:password@localhost:5432/github_data

      - name: Dump Data to CSV
        run: |
          PGPASSWORD=password psql -h localhost -U user -d github_data -c "\COPY (SELECT * FROM github_repos) TO 'results.csv' WITH CSV HEADER"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: crawled-data
          path: results.csv